#!/usr/bin/env python3
"""
Validate the Context Graph Protocol wire examples against the JSON Schema.

Usage:
    python3 schema/validate-examples.py

Exits 0 if every message in examples/, every reference-serialized vector, and
every fenced example in SPEC.md is valid under schema/ — and the schema's `$id`
resolves to a byte-identical served copy. Exits 1 otherwise.
No third-party dependencies beyond `jsonschema` (pip install jsonschema).

The four example surfaces are deliberately different in kind:

  * `examples/` is hand-authored — it proves the schema accepts what a human
    writes, and is what a provider author diffs against.
  * `reference-vectors.ndjson` is machine-serialized from the reference Rust
    types — it proves the schema accepts what the canonical serializer actually
    emits (issue #54). Curated examples cannot catch that class.
  * `SPEC.md` is the normative document. It is checked because it was the one
    example surface nothing validated, and it drifted: the §9 `verify` example
    carried an `id` member that §3.2 grants only to `query`/`frames`/`error`,
    that the reference envelope has no field for, and that the schema's
    `additionalProperties: false` rejects. The spec's own examples are now held
    to the spec's own schema.
  * the served `$id` copy is the schema's public identity — checked because a
    stale schema that still resolves is worse than one that 404s.
"""
import json
import re
import sys
from pathlib import Path

try:
    import jsonschema
except ImportError:
    sys.exit("error: this script needs `jsonschema`. Install it: pip install jsonschema")

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = json.loads((ROOT / "schema" / "contextgraph-envelope.schema.json").read_text())
failures = 0


def check(label: str, ok: bool) -> None:
    global failures
    if ok:
        print(f"  PASS  {label}")
    else:
        print(f"  FAIL  {label}")
        failures += 1


print("Validating examples against schema/contextgraph-envelope.schema.json\n")

# 1. NDJSON transcript — one envelope per line.
ndjson_path = ROOT / "examples" / "full-stdio-session.ndjson"
lines = [l for l in ndjson_path.read_text().splitlines() if l.strip()]
for i, line in enumerate(lines, 1):
    try:
        jsonschema.validate(json.loads(line), SCHEMA)
    except (json.JSONDecodeError, jsonschema.ValidationError) as e:
        check(f"{ndjson_path.name} line {i}", False)
        print(f"        {e}")
        continue
    check(f"{ndjson_path.name} line {i} ({json.loads(line)['type']})", True)

# 2. Pretty-printed reference messages — one envelope per array element.
ref_path = ROOT / "examples" / "reference-messages.json"
for i, msg in enumerate(json.loads(ref_path.read_text())):
    try:
        jsonschema.validate(msg, SCHEMA)
    except jsonschema.ValidationError as e:
        check(f"{ref_path.name} message {i} ({msg.get('type')})", False)
        print(f"        {e}")
        continue
    check(f"{ref_path.name} message {i} ({msg['type']})", True)

# 3. Reference-SERIALIZED vectors — one envelope per line, generated by
#    `contextgraph-conformance/tests/reference_vectors.rs` from the reference
#    Rust types rather than authored by hand.
#
#    This is the half that catches schema/serializer disagreement (issue #54).
#    Curated examples only ever prove the schema accepts what a human wrote; a
#    field marked `required` here but omitted by `skip_serializing_if` in the
#    Rust type stays invisible until some downstream serializes a real value and
#    gets rejected. Validating the serializer's own minimal output — empty vecs,
#    `None` options — makes that class of bug a red build instead of a
#    downstream bug report.
vectors_path = ROOT / "schema" / "reference-vectors.ndjson"
vector_lines = [l for l in vectors_path.read_text().splitlines() if l.strip()]
if not vector_lines:
    sys.exit(f"error: {vectors_path.name} is empty — regenerate it "
             "(REGENERATE_VECTORS=1 cargo test -p contextgraph-conformance --test reference_vectors)")
for i, line in enumerate(vector_lines, 1):
    try:
        jsonschema.validate(json.loads(line), SCHEMA)
    except (json.JSONDecodeError, jsonschema.ValidationError) as e:
        check(f"{vectors_path.name} line {i}", False)
        print(f"        {e}")
        continue
    check(f"{vectors_path.name} line {i} ({json.loads(line)['type']})", True)

# 4. SPEC.md's own fenced examples.
#
#    These are jsonc — `//` comments, and prose placeholders standing in for
#    values whose real form is uninteresting to a reader (`"…"`,
#    `sha256:<64 hex>`). Both are normalized away before validation, because
#    what is being checked here is STRUCTURE: member names, required members,
#    types, and above all `additionalProperties` — the class of error that put
#    an `id` on a `verify`. Substituting a placeholder never invents a member,
#    so it cannot mask that.
ENVELOPE_TYPES = {
    SCHEMA["$defs"][ref["$ref"].rsplit("/", 1)[-1]]["properties"]["type"]["const"]
    for ref in SCHEMA["oneOf"]
}

PLACEHOLDERS = [
    (re.compile(r"sha256:<64 hex>"), "sha256:" + "a" * 64),  # §F5 digest form
    (re.compile(r'"…"'), '"placeholder"'),                   # elided string value
]


def strip_line_comments(text: str) -> str:
    """Remove `//` comments, leaving `//` inside JSON strings alone."""
    out = []
    for line in text.splitlines():
        in_string = escaped = False
        cut = None
        for i, ch in enumerate(line):
            if escaped:
                escaped = False
            elif ch == "\\" and in_string:
                escaped = True
            elif ch == '"':
                in_string = not in_string
            elif ch == "/" and not in_string and line[i + 1 : i + 2] == "/":
                cut = i
                break
        out.append(line if cut is None else line[:cut])
    return "\n".join(out)


def json_values(text: str):
    """Yield each successive JSON value in a block (a block may hold a pair)."""
    decoder = json.JSONDecoder()
    index = 0
    while (index := _skip_ws(text, index)) < len(text):
        value, index = decoder.raw_decode(text, index)
        yield value


def _skip_ws(text: str, index: int) -> int:
    while index < len(text) and text[index] in " \t\r\n":
        index += 1
    return index


spec_path = ROOT / "SPEC.md"
spec_lines = spec_path.read_text().splitlines()
blocks, current, start = [], None, 0
for number, line in enumerate(spec_lines, 1):
    if current is None:
        if line.rstrip() == "```jsonc":
            current, start = [], number
    elif line.rstrip() == "```":
        blocks.append((start, "\n".join(current)))
        current = None
    else:
        current.append(line)

if not blocks:
    check("SPEC.md contains fenced jsonc examples", False)
    print("        no ```jsonc blocks found — did the fence style change?")

for start, block in blocks:
    text = strip_line_comments(block)
    for pattern, replacement in PLACEHOLDERS:
        text = pattern.sub(replacement, text)

    try:
        values = list(json_values(text))
    except json.JSONDecodeError as e:
        check(f"SPEC.md:{start} parses as JSON", False)
        print(f"        {e}")
        continue

    for offset, value in enumerate(values):
        # An envelope validates against the root schema; a bare payload example
        # (§6's frame anatomy) validates against its own $def. Naming the target
        # keeps this auditable rather than magical.
        if isinstance(value, dict) and value.get("type") in ENVELOPE_TYPES:
            target, schema = f"envelope {value['type']}", SCHEMA
        else:
            target = "ContextFrame"
            schema = {
                "$schema": SCHEMA["$schema"],
                "$ref": "#/$defs/ContextFrame",
                "$defs": SCHEMA["$defs"],
            }
        label = f"SPEC.md:{start}"
        if len(values) > 1:
            label += f" [{offset + 1}/{len(values)}]"
        try:
            jsonschema.validate(value, schema)
        except jsonschema.ValidationError as e:
            check(f"{label} ({target})", False)
            print(f"        {e.message}")
            continue
        check(f"{label} ({target})", True)

# 5. The schema's `$id` must dereference to this exact schema.
#
#    `$id` is the schema's public identity — the URL third parties resolve and
#    quote. It pointed at `context-graph-protocol.org`, a hyphenated host that
#    was never registered and returned a DNS failure, so every consumer that
#    tried to fetch it got nothing. Now it names the live domain, and the site
#    serves the file from `site/public/schema/`.
#
#    A served copy can drift from the source of truth, which would be worse than
#    a 404: a stale schema that still resolves is one that silently validates
#    the wrong thing. So the copy is asserted byte-identical here rather than
#    trusted to be refreshed by hand.
SCHEMA_SOURCE = ROOT / "schema" / "contextgraph-envelope.schema.json"
SCHEMA_SERVED = ROOT / "site" / "public" / "schema" / "contextgraph-envelope.schema.json"
expected_id = f"https://contextgraphprotocol.org/schema/{SCHEMA_SOURCE.name}"

check(f"$id is {expected_id}", SCHEMA.get("$id") == expected_id)

if not SCHEMA_SERVED.exists():
    check(f"site serves the schema at {SCHEMA_SERVED.relative_to(ROOT)}", False)
    print(f"        missing — copy it: cp {SCHEMA_SOURCE.relative_to(ROOT)} {SCHEMA_SERVED.relative_to(ROOT)}")
    failures += 1
else:
    identical = SCHEMA_SERVED.read_bytes() == SCHEMA_SOURCE.read_bytes()
    check("the served schema copy is byte-identical to the source", identical)
    if not identical:
        print(f"        refresh it: cp {SCHEMA_SOURCE.relative_to(ROOT)} {SCHEMA_SERVED.relative_to(ROOT)}")

print(f"\n{'OK — all examples validate' if failures == 0 else f'{failures} failure(s)'}")
sys.exit(1 if failures else 0)
