#!/usr/bin/env python3
"""
Validate the Context Graph Protocol wire examples against the JSON Schema.

Usage:
    python3 schema/validate-examples.py

Exits 0 if every message in examples/ is valid under schema/, and 1 otherwise.
No third-party dependencies beyond `jsonschema` (pip install jsonschema).
"""
import json
import sys
from pathlib import Path

try:
    import jsonschema
except ImportError:
    sys.exit("error: this script needs `jsonschema`. Install it: pip install jsonschema")

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = json.loads((ROOT / "schema" / "contextgraph-envelope.schema.json").read_text())
failures = 0


def check(label: str, ok: bool) -> None:
    global failures
    if ok:
        print(f"  PASS  {label}")
    else:
        print(f"  FAIL  {label}")
        failures += 1


print("Validating examples against schema/contextgraph-envelope.schema.json\n")

# 1. NDJSON transcript — one envelope per line.
ndjson_path = ROOT / "examples" / "full-stdio-session.ndjson"
lines = [l for l in ndjson_path.read_text().splitlines() if l.strip()]
for i, line in enumerate(lines, 1):
    try:
        jsonschema.validate(json.loads(line), SCHEMA)
    except (json.JSONDecodeError, jsonschema.ValidationError) as e:
        check(f"{ndjson_path.name} line {i}", False)
        print(f"        {e}")
        continue
    check(f"{ndjson_path.name} line {i} ({json.loads(line)['type']})", True)

# 2. Pretty-printed reference messages — one envelope per array element.
ref_path = ROOT / "examples" / "reference-messages.json"
for i, msg in enumerate(json.loads(ref_path.read_text())):
    try:
        jsonschema.validate(msg, SCHEMA)
    except jsonschema.ValidationError as e:
        check(f"{ref_path.name} message {i} ({msg.get('type')})", False)
        print(f"        {e}")
        continue
    check(f"{ref_path.name} message {i} ({msg['type']})", True)

# 3. Reference-SERIALIZED vectors — one envelope per line, generated by
#    `contextgraph-conformance/tests/reference_vectors.rs` from the reference
#    Rust types rather than authored by hand.
#
#    This is the half that catches schema/serializer disagreement (issue #54).
#    Curated examples only ever prove the schema accepts what a human wrote; a
#    field marked `required` here but omitted by `skip_serializing_if` in the
#    Rust type stays invisible until some downstream serializes a real value and
#    gets rejected. Validating the serializer's own minimal output — empty vecs,
#    `None` options — makes that class of bug a red build instead of a
#    downstream bug report.
vectors_path = ROOT / "schema" / "reference-vectors.ndjson"
vector_lines = [l for l in vectors_path.read_text().splitlines() if l.strip()]
if not vector_lines:
    sys.exit(f"error: {vectors_path.name} is empty — regenerate it "
             "(REGENERATE_VECTORS=1 cargo test -p contextgraph-conformance --test reference_vectors)")
for i, line in enumerate(vector_lines, 1):
    try:
        jsonschema.validate(json.loads(line), SCHEMA)
    except (json.JSONDecodeError, jsonschema.ValidationError) as e:
        check(f"{vectors_path.name} line {i}", False)
        print(f"        {e}")
        continue
    check(f"{vectors_path.name} line {i} ({json.loads(line)['type']})", True)

# 4. The schema's `$id` must dereference to this exact schema.
#
#    `$id` is the schema's public identity — the URL third parties resolve and
#    quote. It pointed at `context-graph-protocol.org`, a hyphenated host that
#    was never registered and returned a DNS failure, so every consumer that
#    tried to fetch it got nothing. Now it names the live domain, and the site
#    serves the file from `site/public/schema/`.
#
#    A served copy can drift from the source of truth, which would be worse than
#    a 404: a stale schema that still resolves is one that silently validates
#    the wrong thing. So the copy is asserted byte-identical here rather than
#    trusted to be refreshed by hand.
SCHEMA_SOURCE = ROOT / "schema" / "contextgraph-envelope.schema.json"
SCHEMA_SERVED = ROOT / "site" / "public" / "schema" / "contextgraph-envelope.schema.json"
expected_id = f"https://contextgraphprotocol.org/schema/{SCHEMA_SOURCE.name}"

check(f"$id is {expected_id}", SCHEMA.get("$id") == expected_id)

if not SCHEMA_SERVED.exists():
    check(f"site serves the schema at {SCHEMA_SERVED.relative_to(ROOT)}", False)
    print(f"        missing — copy it: cp {SCHEMA_SOURCE.relative_to(ROOT)} {SCHEMA_SERVED.relative_to(ROOT)}")
    failures += 1
else:
    identical = SCHEMA_SERVED.read_bytes() == SCHEMA_SOURCE.read_bytes()
    check("the served schema copy is byte-identical to the source", identical)
    if not identical:
        print(f"        refresh it: cp {SCHEMA_SOURCE.relative_to(ROOT)} {SCHEMA_SERVED.relative_to(ROOT)}")

print(f"\n{'OK — all examples validate' if failures == 0 else f'{failures} failure(s)'}")
sys.exit(1 if failures else 0)
